### ISSUE TITLE
AM demodulation suggestions

### ISSUE THREAD

**Issue by FrankBolleri** [librtlsdr/SharpRTL#3]
Hello, thanks for your great work.

I am able to run your example and it works great.
But now I am trying to use the data received from 

`device_SamplesAvailable(ref byte[] data, int length)`

and I don't understand exactly what I have to do.

My goal is to be able to record in a WAV file the AM demodulated signal on a certain frequency.
It is not clear to me what format the returned array `byte[] data` is representing and the steps to successfully convert it in the desired result, using C#.

If you know how to do it, will be great if you can put that function in your SampleApp (or integrate in the library?)

Thanks in advance
Francesco

**Comment by racerxdl** [comment]
Hi!

The format is exactly the same as librtlsdr outputs: 8 Bit IQ (which is basically the only format rtlsdr supports)

So you probably want to convert that to Complex Float and do the math over the signal to demodulate your AM signal.

**Comment by FrankBolleri** [comment]
I will try to understand how to do it... but if there is the chance for you, I think should be a great function to put in SharpRTL.
Thanks and have a nice day.
Francesco
